# Generated by Django 5.0.7 on 2024-08-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registre_national', models.CharField(max_length=11, unique=True, verbose_name='Numéro de registre national')),
                ('numero_externe', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro externe')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
            options={
                'indexes': [models.Index(fields=['numero_registre_national'], name='indalyzer_c_numero__a627ef_idx'), models.Index(fields=['numero_externe'], name='indalyzer_c_numero__956be9_idx'), models.Index(fields=['nom', 'prenom'], name='indalyzer_c_nom_9c3931_idx')],
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accident', models.DateField(blank=True, null=True)),
                ('source_donnees', models.CharField(choices=[('BD', 'Base de données'), ('MANUEL', 'Encodage manuel')], max_length=10)),
                ('type_accident', models.CharField(choices=[('TRAVAIL', 'Accident de travail'), ('COMMUN', 'Droit commun')], default='TRAVAIL', max_length=10)),
                ('statut_chomage', models.CharField(choices=[('NON', 'Non applicable'), ('OCCASIONNEL', 'Chômeur occasionnel'), ('LONGUE_DUREE', 'Chômeur de longue durée')], default='OCCASIONNEL', max_length=15)),
                ('convention_assuralia', models.BooleanField(default=False)),
                ('affilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indalyzer_core.affilie')),
            ],
        ),
        migrations.CreateModel(
            name='CalculIndemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_affilie', models.CharField(max_length=100)),
                ('prenom_affilie', models.CharField(max_length=100)),
                ('numero_registre_national', models.CharField(max_length=11)),
                ('date_naissance', models.DateField()),
                ('type_calcul', models.CharField(choices=[('IET', 'Incapacité Temporaire'), ('IPP', 'Incapacité Permanente Partielle')], max_length=3)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('source_montant', models.CharField(choices=[('CALCULE', 'Calculé automatiquement'), ('RECUPERE', 'Récupéré de données existantes'), ('ENCODE', 'Encodé manuellement')], default='ENCODE', max_length=10)),
                ('salaire_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_incapacite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_consolidation', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_calcule', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_jours', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indalyzer_core.accident')),
                ('affilie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indalyzer_core.affilie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeIndemnisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('taux_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('affilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_indemnisation', to='indalyzer_core.affilie')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
