# Generated by Django 5.0.7 on 2024-08-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='affilie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='indalyzer_core.affilie'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='statut_chomage',
            field=models.CharField(choices=[('NON', 'Non applicable'), ('OCCASIONNEL', 'Chômeur occasionnel'), ('LONGUE_DUREE', 'Chômeur de longue durée')], default='NON_APPLICABLE', max_length=15),
        ),
    ]
