# Generated by Django 5.0.7 on 2024-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0002_alter_accident_affilie_alter_accident_statut_chomage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='type_accident',
            field=models.CharField(choices=[('AT', 'Accident de travail'), ('DC', 'Droit commun'), ('Autre', 'Autre accident')], max_length=6),
        ),
    ]
