# Generated by Django 5.0.7 on 2024-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0003_alter_accident_type_accident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculindemnite',
            name='date_consolidation',
        ),
        migrations.RemoveField(
            model_name='calculindemnite',
            name='salaire_reference',
        ),
        migrations.RemoveField(
            model_name='calculindemnite',
            name='taux_incapacite',
        ),
        migrations.AddField(
            model_name='accident',
            name='date_consolidation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='taux_incapacite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
