# Generated by Django 5.0.7 on 2024-08-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0004_remove_calculindemnite_date_consolidation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='taux_incapacite',
            new_name='taux_ipp',
        ),
    ]
