# Generated by Django 5.0.7 on 2024-08-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0005_rename_taux_incapacite_accident_taux_ipp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='taux_ipp',
            new_name='taux_IPP',
        ),
    ]
