# Generated by Django 5.0.7 on 2024-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0006_rename_taux_ipp_accident_taux_ipp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='taux_IPP',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Taux d'IPP (%)"),
        ),
    ]
