# Generated by Django 5.0.7 on 2024-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0007_alter_accident_taux_ipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculindemnite',
            name='commentaire_texte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculindemnite',
            name='date_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculindemnite',
            name='nouveau_salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculindemnite',
            name='pourcentage_ipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calculindemnite',
            name='type_commentaire',
            field=models.CharField(choices=[('IPP', "Reconnaissance d'une IPP"), ('AGGRAVATION', "Aggravation d'une IPP"), ('ITT', "Reconnaissance d'une ITT à 100%"), ('SALAIRE', 'Modification du salaire de base'), ('AUTRE', 'Autre (texte libre)')], default='AUTRE', max_length=20),
        ),
    ]
