# Generated by Django 5.0.7 on 2024-09-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0008_calculindemnite_commentaire_texte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='est_temporaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affilie',
            name='est_temporaire',
            field=models.BooleanField(default=False),
        ),
    ]
