# Generated by Django 5.0.7 on 2024-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indalyzer_core', '0009_accident_est_temporaire_affilie_est_temporaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilie',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
